version: '3.9'
services:

  mysql:
    image: mysql
    restart: always
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgres:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  node:
    build: ./gate-simulator
    ports:
      - '9999:9999'